// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetStore.Data;

#nullable disable

namespace PetStore.Migrations
{
    [DbContext(typeof(PetStoreContext))]
    partial class PetStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PetStore.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Breed = "Golden Retriever",
                            Category = "Dog",
                            Description = "Friendly, loyal, and ready for a home.",
                            ImageUrl = "images/dog1.jpg",
                            Name = "Max"
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Breed = "Siamese",
                            Category = "Cat",
                            Description = "Curious, calm, and full of personality.",
                            ImageUrl = "images/cat1.jpg",
                            Name = "Luna"
                        },
                        new
                        {
                            Id = 3,
                            Age = 100,
                            Breed = "Mini Flame",
                            Category = "Dragon",
                            Description = "Magical companion with fiery charm.",
                            ImageUrl = "images/dragon1.jpg",
                            Name = "Draco"
                        },
                        new
                        {
                            Id = 4,
                            Age = 5,
                            Breed = "Silver Mane",
                            Category = "Unicorn",
                            Description = "Rare, graceful, and full of wonder.",
                            ImageUrl = "images/unicorn1.jpg",
                            Name = "Sparkle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
