// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetStore.Data;

#nullable disable

namespace PetStore.Migrations
{
    [DbContext(typeof(PetStoreContext))]
    partial class PetStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PetStore.Models.ApplicationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AgreeToTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<string>("FosterLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HelpType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HousingStatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherPets")
                        .HasColumnType("TEXT");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, City, State, 12345",
                            AgreeToTerms = false,
                            Email = "john@example.com",
                            FullName = "John Doe",
                            HelpType = "Adopt",
                            PetName = "Max",
                            PhoneNumber = "555-1234",
                            SubmittedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 Main St, City, State, 12345",
                            AgreeToTerms = false,
                            Email = "jane@example.com",
                            FullName = "Jane Smith",
                            HelpType = "Foster",
                            PetName = "Majesty",
                            PhoneNumber = "555-5678",
                            SubmittedAt = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PetStore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PetStore.Models.Pet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is_Adopt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_Foster")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_Friendly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Shelter_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Breed = "Golden Retriever",
                            Description = "Friendly, loyal, and ready for a home.",
                            Energy = 4,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/goldenr.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Max",
                            Shelter_id = "SHELTER-01",
                            Type = "dogs",
                            YearOfBirth = 2021
                        },
                        new
                        {
                            Id = "2",
                            Breed = "Persian",
                            Description = "Curious, calm, and full of personality.",
                            Energy = 3,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/persian.jpg",
                            Is_Adopt = true,
                            Is_Foster = false,
                            Is_Friendly = true,
                            Name = "Majesty",
                            Shelter_id = "SHELTER-02",
                            Type = "cats",
                            YearOfBirth = 2022
                        },
                        new
                        {
                            Id = "3",
                            Breed = "Netherland Dwarf",
                            Description = "Magical companion with fiery charm.",
                            Energy = 5,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/netherland-dwarf.jpg",
                            Is_Adopt = false,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Tiny",
                            Shelter_id = "SHELTER-06",
                            Type = "rabbits",
                            YearOfBirth = 2010
                        },
                        new
                        {
                            Id = "4",
                            Breed = "Hedgehog",
                            Description = "Rare, shy, and full of wonder.",
                            Energy = 2,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/hedgehog.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Sparkle",
                            Shelter_id = "SHELTER-04",
                            Type = "exotics",
                            YearOfBirth = 2019
                        },
                        new
                        {
                            Id = "5",
                            Breed = "Maltese",
                            Description = "Intelligent and handsome. He just loves to be with you.",
                            Energy = 3,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/maltese.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Cloud",
                            Shelter_id = "SHELTER-01",
                            Type = "dogs",
                            YearOfBirth = 2023
                        },
                        new
                        {
                            Id = "6",
                            Breed = "Bearded Dragon",
                            Description = "Curious, adorable, and intelligent.",
                            Energy = 2,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/bearded-dragon.jpg",
                            Is_Adopt = false,
                            Is_Foster = false,
                            Is_Friendly = false,
                            Name = "Jimbo",
                            Shelter_id = "SHELTER-05",
                            Type = "exotics",
                            YearOfBirth = 2020
                        },
                        new
                        {
                            Id = "7",
                            Breed = "Orange Tabby",
                            Description = "Majestic, regal, and content. All she wants is to lay in the sun.",
                            Energy = 5,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/orange-cat.jpg",
                            Is_Adopt = false,
                            Is_Foster = false,
                            Is_Friendly = true,
                            Name = "Raja",
                            Shelter_id = "SHELTER-02",
                            Type = "cats",
                            YearOfBirth = 2017
                        },
                        new
                        {
                            Id = "8",
                            Breed = "White Cockatoo",
                            Description = "Loves to talk, sing, and dance.",
                            Energy = 5,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/white-parrot.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Marshmallow",
                            Shelter_id = "SHELTER-03",
                            Type = "birds",
                            YearOfBirth = 2014
                        },
                        new
                        {
                            Id = "9",
                            Breed = "Parrot",
                            Description = "He's a living rainforest ready to go home with you.",
                            Energy = 5,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/parrot.jpg",
                            Is_Adopt = true,
                            Is_Foster = true,
                            Is_Friendly = true,
                            Name = "Sir Zir",
                            Shelter_id = "SHELTER-03",
                            Type = "birds",
                            YearOfBirth = 2022
                        },
                        new
                        {
                            Id = "10",
                            Breed = "Ferret",
                            Description = "Only wants to be by you and follow you everywhere.",
                            Energy = 4,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/ferret.jpg",
                            Is_Adopt = true,
                            Is_Foster = false,
                            Is_Friendly = true,
                            Name = "Squishy",
                            Shelter_id = "SHELTER-06",
                            Type = "exotics",
                            YearOfBirth = 2025
                        },
                        new
                        {
                            Id = "11",
                            Breed = "Sugar Glider",
                            Description = "Comes out and plays all night.",
                            Energy = 3,
                            ImageUrl = "https://raw.githubusercontent.com/vsyang/pet-images/main/sugar-glider.jpg",
                            Is_Adopt = true,
                            Is_Foster = false,
                            Is_Friendly = true,
                            Name = "Sweety",
                            Shelter_id = "SHELTER-04",
                            Type = "exotics",
                            YearOfBirth = 2024
                        });
                });

            modelBuilder.Entity("PetStore.PetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PetCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "dogs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "cats"
                        },
                        new
                        {
                            Id = 3,
                            Name = "rabbits"
                        },
                        new
                        {
                            Id = 4,
                            Name = "birds"
                        },
                        new
                        {
                            Id = 5,
                            Name = "exotics"
                        });
                });

            modelBuilder.Entity("PetStore.Shelter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = "SHELTER-01",
                            Country = "US",
                            Email = "contact@goldenpawsrescue.org",
                            Name = "Golden Paws Rescue",
                            State = "Pennsylvania",
                            User_id = "user_01"
                        },
                        new
                        {
                            Id = "SHELTER-02",
                            Country = "CA",
                            Email = "hello@whiskerhaven.org",
                            Name = "Whisker Haven",
                            State = "Ontario",
                            User_id = "user_02"
                        },
                        new
                        {
                            Id = "SHELTER-03",
                            Country = "AU",
                            Email = "info@safewingssanctuary.org",
                            Name = "Safe Wings Sanctuary",
                            State = "New South Wales",
                            User_id = "user_03"
                        },
                        new
                        {
                            Id = "SHELTER-04",
                            Country = "VE",
                            Email = "support@cloudinthesky.org",
                            Name = "Cloud in the Sky",
                            State = "Mérida",
                            User_id = "user_04"
                        },
                        new
                        {
                            Id = "SHELTER-05",
                            Country = "ZA",
                            Email = "team@wildheartrefuge.org",
                            Name = "Wild Heart Refuge",
                            State = "Western Cape",
                            User_id = "user_05"
                        },
                        new
                        {
                            Id = "SHELTER-06",
                            Country = "MX",
                            Email = "care@hopetailsshelter.org",
                            Name = "Hope Tails Shelter",
                            State = "Guanajuato",
                            User_id = "user_06"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
